# Generated by Django 2.2.4 on 2020-01-22 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('oily', models.CharField(max_length=10)),
                ('dry', models.CharField(max_length=10)),
                ('sensitivity', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='quantity',
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('BASE', 'basemakeup'), ('SUNC', 'suncare'), ('MASK', 'maskpack'), ('SKIN', 'skincare')], default=None, max_length=32),
        ),
        migrations.AddField(
            model_name='item',
            name='gender',
            field=models.CharField(choices=[('M', 'male'), ('F', 'female'), ('A', 'all')], default='A', max_length=10),
        ),
        migrations.AddField(
            model_name='item',
            name='imageId',
            field=models.CharField(max_length=37, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='monthlySales',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='ingredients',
            field=models.ManyToManyField(to='item.Ingredient'),
        ),
    ]
