# Generated by Django 2.2.4 on 2020-01-23 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20200122_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='dry',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='oily',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='sensitivity',
            field=models.IntegerField(default=0),
        ),
    ]
