# Generated by Django 2.2.4 on 2020-01-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_auto_20200123_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ingredient_string',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('basemakeup', 'basemakeup'), ('suncare', 'suncare'), ('maskpack', 'maskpack'), ('skincare', 'skincare')], default=None, max_length=32),
        ),
    ]
